# -*- coding: utf-8 -*-
"""2211CS020039(15th march 2025).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFIsa5dLCfPgHkMch9TdIg0lTUbEyYTm
"""

import google.generativeai as genai
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key='GOOGLE_API_KEY')

import PyPDF2
def extract_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, "rb") as pdf_file:
        reader = PyPDF2.PdfReader(pdf_file)
        for page in reader.pages:
            text += page.extract_text()+"\n"
    return text

import google.generativeai as genai
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

pip install PyPDF2

def extract_health_insights(text):
  model=genai.GenerativeModel("gemini-1.5-flash")
  prompt=f"Extract key insights from the following health report:\n\n{text}"
  response=model.generate_content(prompt)
  return response.text
pdf_file="health_report.pdf"
extracted_text=extract_text_from_pdf(pdf_file)
insights=extract_health_insights(extracted_text)
print("Key Insights:\n",insights)

def detect_abnormalities(text):
  model=genai.GenerativeModel("gemini-1.5-flash")
  prompt=f"Analyze the lab test results in the following health report and highlight any abnormal values:\n\n{text}"
  response=model.generate_content(prompt)
  return response.text
abnormalities=detect_abnormalities(extracted_text)
print("Potential Abnormalities:\n",abnormalities)

def explain_medical_terms(text):
  model=genai.GenerativeModel("gemini-1.5-flash")
  prompt=f"Explain the medical terms in the following health report in simple language:\n\n{text}"
  response=model.generate_content(prompt)
  return response.text
explanation=explain_medical_terms(extracted_text)
print("Simplified Explanation:\n",explanation)

