# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fOx1f-zzZ4VOfQA9RPOdsJP8mMisWEV
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U -q "google-generativeai>=0.7.2"

import google.generativeai as genai
from google.colab import userdata
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

model=genai.GenerativeModel('models/gemini-2.0-flash')
response=model.generate_content("Please give me python code to sort a list.")
print(response.text)

